### ISSUE TITLE
When I am trying to install in laravel 6.2 version it's showing error

### ISSUE THREAD

**Issue by RakibRizan** [Javaabu/bml-connect-laravel#1]
[InvalidArgumentException]
  Could not find a matching version of package javaabu/bml-connect-laravel. Check the package spelling, your version
  constraint and that the package is available in a stability which matches your minimum-stability (dev).

require [--dev] [--prefer-source] [--prefer-dist] [--fixed] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...

**Comment by dash8x** [comment]
Sorry, I haven't published this package on packagist yet. For now if you want to use this package in your project, you can add the following to your composer.json file

``` json
"repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/javaabu/bml-connect-laravel.git"
        }
    ],
```

**Comment by dash8x** [comment]
Sorry, it wasn't published to packagist. Now I've published it. Please check now.
